### ISSUE TITLE
Question about supported device

### ISSUE THREAD

**Issue by mengniwang95** [pytorch/ort#98]
Hi, I find if I want to install torch-ort, I must install cuda dependency first. But in bert example, it also supports CPU running. So I wonder the request of cuda dependency for installation is necessary?

**Comment by wschin** [comment]
Most optimization techniques of ORT target large models. When running big model, we assume GPU is needed, so users need to install Pytorch with GPU support. Here is an example -- [ORT for training always expects a Pytorch allocator available](https://github.com/microsoft/onnxruntime/blob/6420530b3a71c84d66e1f79b27d16df952ca4fdd/cmake/onnxruntime_python.cmake#L307).

**Comment by thiagocrepaldi** [comment]
@mengniwang95 Although it is possible to run using CPU only, ONNX Runtime does not prioritize it on its roadmap.
Many models will not be trainable on CPU only due to missing operators or because they are just to big for the poor CPU

Maybe you can try start with CPU only to get started and migrate to CUDA or ROCM when you need to train more complex models
